-- ============================================
-- DMS 매뉴얼 데이터 Supabase 저장 SQL
-- ============================================
-- 실행 방법:
-- 1. Supabase Dashboard > SQL Editor 접속
-- 2. 이 스크립트 전체를 복사하여 붙여넣기
-- 3. "Run" 버튼 클릭
-- ============================================

INSERT INTO kv_store_8aea8ee5 (key, value)
VALUES (
  'dms_manual_data_v1',
  '{
    "translations": {
      "ko": {
        "category.start": "DMS 시작하기",
        "category.login": "DMS 로그인/회원가입",
        "category.app": "DMS-상식플러스(App) 연동",
        "category.member": "DMS 회원 관리",
        "category.recipe": "기관 레시피 관리",
        "category.settings": "DMS 설정",
        "category.notice": "서비스 공지사항",
        "section.start.features": "DMS 시작하기",
        "section.login.admin": "관리자 로그인",
        "section.login.member": "회원 앱 가입 안내",
        "section.app.intro": "상식플러스 앱 소개",
        "section.app.connection": "DMS-상식플러스(App) 연결",
        "section.member.dashboard": "회원 대시보드",
        "section.member.info": "회원 정보 관리",
        "section.member.meal": "식사 기록 관리",
        "section.member.nutrition": "영양 리포트",
        "section.member.consult": "온라인 상담",
        "section.recipe.create": "레시피 생성",
        "section.recipe.manage": "레시피 관리",
        "section.settings.institution": "기관 설정",
        "section.settings.members": "기관 구성원 관리",
        "section.settings.etc": "기타 설정",
        "section.notice.list": "공지사항 목록",
        "login-admin.title": "관리자 로그인",
        "login-admin.intro": "DMS 웹 대시보드는 병원 및 영양 관리 기관의 전문가를 위한 관리 시스템입니다. 회원의 식단·영양 데이터·상담 이력을 통합 관리하고 AI 기반 분석 결과를 확인할 수 있습니다.",
        "login-admin.guide-title": "로그인 방법",
        "login-admin.step1.title": "DMS 웹사이트 접속",
        "login-admin.step1.desc": "DMS 웹 대시보드 URL을 통해 로그인 페이지에 접속합니다. 기관별로 제공된 전용 URL을 사용하세요.",
        "login-admin.step2.title": "관리자 계정으로 로그인",
        "login-admin.step2.desc": "기관 담당자로부터 전달받은 관리자 아이디와 비밀번호를 입력합니다. 최초 로그인 시 비밀번호 변경이 필요할 수 있습니다.",
        "login-admin.step3.title": "대시보드 확인",
        "login-admin.step3.desc": "로그인 성공 후 회원 대시보드가 표시됩니다. 좌측 메뉴에서 원하는 기능을 선택하여 사용할 수 있습니다.",
        "login-admin.tip-title": "💡 로그인 문제 해결",
        "login-admin.tip-desc": "로그인이 되지 않거나 비밀번호를 분실한 경우 기관 담당자 또는 DMS 고객지원팀(sales@doinglab.com)으로 문의하세요.",
        "login-member.title": "회원 앱 가입 안내",
        "login-member.intro": "DMS 회원은 상식플러스 모바일 앱을 통해 식단 기록·AI 영양 분석·전문가 상담 등의 서비스를 이용합니다. 관리자가 회원 계정을 생성한 후 회원에게 앱 다운로드를 안내합니다.",
        "login-member.guide-title": "회원 앱 가입 절차",
        "login-member.step1.title": "상식플러스 앱 다운로드 안내",
        "login-member.step1.desc": "회원에게 앱스토어(iOS) 또는 구글 플레이스토어(Android)에서 상식플러스 앱을 다운로드하도록 안내합니다.",
        "login-member.step2.title": "회원 계정 생성",
        "login-member.step2.desc": "관리자가 DMS 웹 대시보드 회원 관리 메뉴에서 회원 정보(이름·연락처·이메일 등)를 입력하여 계정을 생성합니다.",
        "login-member.step3.title": "로그인 정보 전달",
        "login-member.step3.desc": "생성된 아이디와 초기 비밀번호를 회원에게 문자·이메일 등으로 안전하게 전달합니다.",
        "login-member.step4.title": "앱 로그인 및 초기 설정",
        "login-member.step4.desc": "회원이 앱에서 전달받은 정보로 로그인하고 비밀번호 변경 및 전자문진표 작성 등 초기 설정을 완료합니다.",
        "login-member.step5.title": "기관 연동 확인",
        "login-member.step5.desc": "회원이 앱에서 기관 코드를 입력하거나 자동 연동되면 DMS 대시보드에서 해당 회원의 데이터를 실시간으로 확인할 수 있습니다.",
        "app-intro.title": "상식플러스 앱 소개",
        "app-intro.intro": "상식플러스는 회원이 직접 식단을 기록하고 AI 기반 영양 분석을 받을 수 있는 모바일 앱입니다. DMS와 실시간 연동되어 관리자가 회원의 식단과 건강 데이터를 모니터링할 수 있습니다.",
        "app-intro.guide-title": "상식플러스 앱 주요 기능",
        "app-intro.step1.title": "식단 사진 촬영 및 기록",
        "app-intro.step1.desc": "회원이 식사 사진을 촬영하면 AI가 자동으로 음식을 인식하고 기록합니다. 간편하게 아침·점심·저녁·간식을 구분하여 기록할 수 있습니다.",
        "app-intro.step2.title": "AI 영양소 자동 분석",
        "app-intro.step2.desc": "촬영된 식단의 칼로리·탄수화물·단백질·지방 등 영양소를 AI가 자동으로 분석합니다. 분석 결과는 실시간으로 DMS에 연동됩니다.",
        "app-intro.step3.title": "1:1 채팅 상담",
        "app-intro.step3.desc": "회원이 앱 내 채팅 기능을 통해 담당 영양사 또는 상담사와 실시간으로 소통할 수 있습니다. 식단 피드백과 건강 조언을 받을 수 있습니다.",
        "app-intro.step4.title": "혈당 모니터링 (CGM 연동)",
        "app-intro.step4.desc": "CGM(연속혈당측정) 기기와 연동하여 혈당 데이터를 실시간으로 확인할 수 있습니다. 식사 전후 혈당 변화를 그래프로 제공합니다.",
        "app-intro.step5.title": "전자문진표 작성",
        "app-intro.step5.desc": "최초 가입 시 또는 정기적으로 전자문진표를 작성하여 건강 상태·식습관·알레르기 정보 등을 관리자에게 전달합니다.",
        "app-intro.step6.title": "맞춤 레시피 제공",
        "app-intro.step6.desc": "기관에서 등록한 맞춤형 레시피를 회원이 앱에서 확인하고 활용할 수 있습니다. 개인 목표 칼로리에 맞는 레시피를 추천받습니다.",
        "app-connection.title": "DMS-상식플러스(App) 연결",
        "app-connection.intro": "DMS 백오피스와 상식플러스 앱을 연동하면 회원의 식단 기록·영양 분석 데이터·혈당 정보 등이 실시간으로 동기화됩니다. 아래 절차에 따라 연동을 설정하세요.",
        "app-connection.guide-title": "앱 연동 가이드",
        "app-connection.step1.title": "기관 설정 메뉴 접속",
        "app-connection.step1.desc": "DMS 백오피스 좌측 메뉴에서 설정 > 기관 설정을 선택합니다.",
        "app-connection.step2.title": "앱 연동 활성화",
        "app-connection.step2.desc": "기관 설정 페이지에서 앱 연동 섹션을 찾아 e-눈 ON 버튼을 클릭하여 연동을 활성화합니다.",
        "app-connection.step3.title": "기관 코드 확인 및 복사",
        "app-connection.step3.desc": "연동 활성화 후 생성된 고유 기관 코드를 확인하고 복사합니다. 이 코드는 회원이 앱에서 기관을 찾을 때 사용됩니다.",
        "app-connection.step4.title": "회원에게 기관 코드 전달",
        "app-connection.step4.desc": "복사한 기관 코드를 회원에게 문자·이메일·또는 직접 안내하여 앱에서 입력하도록 합니다.",
        "app-connection.step5.title": "연동 상태 확인",
        "app-connection.step5.desc": "회원이 앱에서 기관 코드를 입력하고 연동하면 DMS 대시보드에서 연동된 회원 수와 데이터를 실시간으로 확인할 수 있습니다.",
        "app-connection.tip-title": "💡 CGM 연동 참고사항",
        "app-connection.tip-desc": "CGM 기기 연동은 회원이 앱에서 직접 설정합니다. 연동 가능한 기기 종류와 설정 방법은 앱 내 설정 > CGM 연동 메뉴에서 확인할 수 있습니다.",
        "member-dashboard.title": "회원 대시보드",
        "member-dashboard.intro": "회원 대시보드에서는 기관에 등록된 전체 회원의 현황을 한눈에 파악할 수 있습니다. 회원 목록 조회·검색·필터링 등의 기능을 통해 효율적으로 회원을 관리하세요.",
        "member-dashboard.guide-title": "회원 대시보드 사용 가이드",
        "member-dashboard.step1.title": "회원 목록 조회",
        "member-dashboard.step1.desc": "좌측 메뉴에서 회원 관리를 클릭하면 등록된 전체 회원 목록이 표시됩니다. 이름·등록일·최근 활동일 등 기본 정보를 확인할 수 있습니다.",
        "member-dashboard.step2.title": "회원 검색 및 필터링",
        "member-dashboard.step2.desc": "상단 검색창에서 이름·이메일·전화번호로 회원을 검색할 수 있습니다. 상태(활성/비활성)·등록 기간 등으로 필터링도 가능합니다.",
        "member-dashboard.step3.title": "회원 상세 정보 접근",
        "member-dashboard.step3.desc": "회원 이름을 클릭하면 해당 회원의 상세 정보 페이지로 이동합니다. 기본 정보·식단 기록·영양 분석·상담 이력 등을 확인할 수 있습니다.",
        "member-dashboard.step4.title": "신규 회원 등록",
        "member-dashboard.step4.desc": "회원 추가 버튼을 클릭하여 새로운 회원을 등록합니다. 필수 정보(이름·연락처)를 입력하면 앱 로그인 계정이 자동 생성됩니다.",
        "member-info.title": "회원 정보 관리",
        "member-info.intro": "개별 회원의 기본 정보·건강 정보·목표 설정 등을 조회하고 수정할 수 있습니다. 회원의 전자문진표 응답 내용과 Raw data도 확인 가능합니다.",
        "member-info.guide-title": "회원 정보 관리 가이드",
        "member-info.step1.title": "기본 정보 확인",
        "member-info.step1.desc": "회원의 이름·연락처·이메일·생년월일·성별 등 기본 정보를 확인합니다. 수정 버튼을 클릭하여 정보를 업데이트할 수 있습니다.",
        "member-info.step2.title": "건강 정보 조회",
        "member-info.step2.desc": "신장·체중·목표 체중·활동량·기저질환 등 건강 관련 정보를 확인합니다. 전자문진표 작성 내용이 자동으로 반영됩니다.",
        "member-info.step3.title": "Raw Data 확인",
        "member-info.step3.desc": "회원의 앱 사용 로그·식단 기록 원본 데이터 등 상세 데이터를 확인할 수 있습니다. 데이터 분석 시 활용하세요.",
        "member-info.step4.title": "목표 설정 및 수정",
        "member-info.step4.desc": "회원의 일일 목표 칼로리(예: 2000kcal)·영양소 비율·식사 횟수 등을 설정하거나 수정합니다.",
        "member-info.step5.title": "메모 작성",
        "member-info.step5.desc": "회원별 특이사항이나 상담 시 참고할 내용을 메모로 기록합니다. 다른 관리자도 확인할 수 있습니다.",
        "member-info.step6.title": "1:1 채팅 이력 조회",
        "member-info.step6.desc": "회원과의 채팅 상담 이력을 시간순으로 확인할 수 있습니다. 이전 상담 내용을 참고하여 연속적인 관리가 가능합니다.",
        "member-meal.title": "식사 기록 관리",
        "member-meal.intro": "회원이 상식플러스 앱에서 기록한 식단을 조회하고 관리합니다. AI가 분석한 영양 정보를 확인하고 필요 시 수정하거나 피드백을 제공할 수 있습니다.",
        "member-meal.guide-title": "식사 기록 관리 가이드",
        "member-meal.step1.title": "식단 기록 조회",
        "member-meal.step1.desc": "회원별·날짜별로 아침/점심/저녁/간식 식단 기록을 조회합니다. 캘린더 뷰 또는 리스트 뷰로 확인할 수 있습니다.",
        "member-meal.step2.title": "식사 사진 확인",
        "member-meal.step2.desc": "회원이 업로드한 식사 사진을 클릭하여 크게 볼 수 있습니다. AI가 인식한 음식 목록과 함께 표시됩니다.",
        "member-meal.step3.title": "AI 영양 분석 결과 확인",
        "member-meal.step3.desc": "AI가 자동 분석한 칼로리·탄수화물·단백질·지방 정보를 확인합니다. 음식별 상세 영양 정보도 제공됩니다.",
        "member-meal.step4.title": "영양 정보 수정",
        "member-meal.step4.desc": "AI 분석이 부정확한 경우 관리자가 직접 음식 종류나 양을 수정하여 정확한 영양 정보를 반영할 수 있습니다.",
        "member-meal.step5.title": "피드백 작성 및 전송",
        "member-meal.step5.desc": "개별 식단에 대한 피드백(잘한 점·개선점·조언 등)을 작성합니다. 작성된 피드백은 회원 앱으로 푸시 알림과 함께 전송됩니다.",
        "member-meal.step6.title": "기록 내보내기",
        "member-meal.step6.desc": "특정 기간의 식단 기록과 영양 분석 결과를 엑셀 또는 PDF로 내보낼 수 있습니다. 상담 자료로 활용하세요.",
        "member-nutrition.title": "영양 리포트",
        "member-nutrition.intro": "회원의 영양 섭취 현황을 분석한 주간/월간 리포트를 생성하고 관리합니다. 목표 대비 달성률·영양소별 섭취 추이 등을 시각적으로 확인할 수 있습니다.",
        "member-nutrition.guide-title": "영양 리포트 가이드",
        "member-nutrition.step1.title": "영양 섭취 현황 확인",
        "member-nutrition.step1.desc": "회원의 최근 7일간 평균 칼로리·탄수화물·단백질·지방 섭취량을 확인합니다. 목표 대비 달성률이 그래프로 표시됩니다.",
        "member-nutrition.step2.title": "혈당 그래프 확인 (CGM)",
        "member-nutrition.step2.desc": "CGM 연동 회원의 경우 식사 전후 혈당 변화 그래프를 확인할 수 있습니다. 혈당 스파이크 구간을 식별하는 데 활용하세요.",
        "member-nutrition.step3.title": "주간/월간 리포트 생성",
        "member-nutrition.step3.desc": "기간을 선택하고 리포트 생성 버튼을 클릭하면 종합 영양 분석 리포트가 자동으로 생성됩니다.",
        "member-nutrition.step4.title": "리포트 다운로드 및 공유",
        "member-nutrition.step4.desc": "생성된 리포트를 PDF로 다운로드하거나 이메일로 회원에게 직접 발송할 수 있습니다.",
        "member-nutrition.tip-title": "💡 리포트 활용 팁",
        "member-nutrition.tip-desc": "영양 리포트는 정기 상담 시 회원과 함께 검토하면 효과적입니다. 목표 달성률이 낮은 영양소를 중심으로 식단 개선 방향을 제안해 보세요.",
        "member-consult.title": "온라인 상담",
        "member-consult.intro": "회원과의 1:1 채팅 상담·전자문진표 응답 확인·상담 이력 관리 등 온라인 상담 관련 기능을 제공합니다. 체계적인 상담 기록으로 맞춤형 영양 관리를 지원하세요.",
        "member-consult.guide-title": "온라인 상담 가이드",
        "member-consult.step1.title": "1:1 채팅 상담",
        "member-consult.step1.desc": "회원이 앱에서 보낸 메시지를 확인하고 답변합니다. 식단 사진·질문·건강 고민 등에 대해 실시간으로 소통할 수 있습니다.",
        "member-consult.step2.title": "전자문진표 응답 확인",
        "member-consult.step2.desc": "회원이 작성한 전자문진표 내용을 확인합니다. 건강 상태·식습관·알레르기·복용 약물 등의 정보가 포함되어 있습니다.",
        "member-consult.step3.title": "상담 이력 조회",
        "member-consult.step3.desc": "해당 회원과의 과거 상담 기록을 시간순으로 조회합니다. 이전 상담 내용을 참고하여 일관된 관리를 제공합니다.",
        "member-consult.step4.title": "상담 메모 작성",
        "member-consult.step4.desc": "상담 중 중요한 내용이나 향후 상담 시 참고할 사항을 메모로 기록합니다. 다른 관리자와 공유됩니다.",
        "member-consult.step5.title": "상담 완료 처리",
        "member-consult.step5.desc": "상담이 완료되면 완료 버튼을 클릭합니다. 회원에게 상담 완료 알림이 발송되고 상담 이력에 기록됩니다.",
        "member-consult.tip-title": "💡 효과적인 상담 팁",
        "member-consult.tip-desc": "상담 전 회원의 최근 식단 기록과 영양 리포트를 미리 확인하면 더 구체적이고 맞춤화된 조언을 제공할 수 있습니다."
      },
      "en": {
        "category.start": "Getting Started with DMS",
        "category.login": "DMS Login/Sign Up",
        "category.app": "App - SangsikPlus Connection",
        "category.member": "DMS Member Management",
        "category.recipe": "Institution Recipe Management",
        "category.settings": "DMS Settings",
        "category.notice": "Service Notices",
        "section.start.features": "Getting Started with DMS",
        "section.login.admin": "Admin Login",
        "section.login.member": "Member App Registration Guide",
        "section.app.intro": "SangsikPlus App Introduction",
        "section.app.connection": "DMS-SangsikPlus(App) Connection",
        "section.member.dashboard": "Member Dashboard",
        "section.member.info": "Member Information Management",
        "section.member.meal": "Meal Record Management",
        "section.member.nutrition": "Nutrition Report",
        "section.member.consult": "Online Consultation",
        "section.recipe.create": "Recipe Creation",
        "section.recipe.manage": "Recipe Management",
        "section.settings.institution": "Institution Settings",
        "section.settings.members": "Institution Member Management",
        "section.settings.etc": "Other Settings",
        "section.notice.list": "Notice List",
        "login-admin.title": "Admin Login",
        "login-admin.intro": "The DMS web dashboard is a management system for professionals at hospitals and nutrition management institutions. You can manage member diets and nutrition data and consultation history and check AI-based analysis results.",
        "login-admin.guide-title": "How to Login",
        "login-admin.step1.title": "Access DMS Website",
        "login-admin.step1.desc": "Access the login page through the DMS web dashboard URL. Use the dedicated URL provided for your institution.",
        "login-admin.step2.title": "Login with Admin Account",
        "login-admin.step2.desc": "Enter the admin ID and password provided by the institution manager. You may need to change your password on first login.",
        "login-admin.step3.title": "Check Dashboard",
        "login-admin.step3.desc": "After successful login the member dashboard will be displayed. You can select and use desired features from the left menu.",
        "login-admin.tip-title": "💡 Login Troubleshooting",
        "login-admin.tip-desc": "If you cannot login or have lost your password please contact your institution manager or DMS customer support (sales@doinglab.com).",
        "login-member.title": "Member App Registration Guide",
        "login-member.intro": "DMS members use the SangsikPlus mobile app for diet logging and AI nutrition analysis and expert consultation. After the admin creates a member account guide members to download the app.",
        "login-member.guide-title": "Member App Registration Process",
        "login-member.step1.title": "Guide to Download SangsikPlus App",
        "login-member.step1.desc": "Guide members to download the SangsikPlus app from App Store (iOS) or Google Play Store (Android).",
        "login-member.step2.title": "Create Member Account",
        "login-member.step2.desc": "Admin creates an account by entering member information (name and contact and email etc.) in the Member Management menu of the DMS web dashboard.",
        "login-member.step3.title": "Deliver Login Information",
        "login-member.step3.desc": "Securely deliver the generated ID and initial password to members via text message or email.",
        "login-member.step4.title": "App Login and Initial Setup",
        "login-member.step4.desc": "Member logs in with the received information and completes initial setup including password change and electronic questionnaire.",
        "login-member.step5.title": "Verify Institution Connection",
        "login-member.step5.desc": "When member enters institution code or auto-connects in the app you can check member data in real-time on the DMS dashboard.",
        "app-intro.title": "SangsikPlus App Introduction",
        "app-intro.intro": "SangsikPlus is a mobile app where members can record their diet and receive AI-based nutrition analysis. It syncs with DMS in real-time allowing administrators to monitor member diet and health data.",
        "app-intro.guide-title": "SangsikPlus App Key Features",
        "app-intro.step1.title": "Photo-based Diet Recording",
        "app-intro.step1.desc": "When members take meal photos AI automatically recognizes and records the food. Easily record breakfast and lunch and dinner and snacks separately.",
        "app-intro.step2.title": "AI Automatic Nutrition Analysis",
        "app-intro.step2.desc": "AI automatically analyzes calories and carbohydrates and protein and fat and other nutrients from the photographed meal. Results sync to DMS in real-time.",
        "app-intro.step3.title": "1:1 Chat Consultation",
        "app-intro.step3.desc": "Members can communicate in real-time with their assigned nutritionist or counselor through the in-app chat feature. Receive diet feedback and health advice.",
        "app-intro.step4.title": "Blood Sugar Monitoring (CGM Integration)",
        "app-intro.step4.desc": "Connect with CGM (Continuous Glucose Monitoring) devices to check blood sugar data in real-time. View blood sugar changes before and after meals in graphs.",
        "app-intro.step5.title": "Electronic Questionnaire",
        "app-intro.step5.desc": "Complete electronic questionnaires at initial registration or periodically to share health status and eating habits and allergy information with administrators.",
        "app-intro.step6.title": "Personalized Recipe Recommendations",
        "app-intro.step6.desc": "Members can view and use customized recipes registered by the institution in the app. Receive recipe recommendations matching personal calorie goals.",
        "app-connection.title": "DMS-SangsikPlus(App) Connection",
        "app-connection.intro": "When you connect DMS back office with SangsikPlus app member diet records and nutrition analysis data and blood sugar information sync in real-time. Follow the steps below to set up the connection.",
        "app-connection.guide-title": "App Connection Guide",
        "app-connection.step1.title": "Access Institution Settings Menu",
        "app-connection.step1.desc": "Select Settings > Institution Settings from the left menu in DMS back office.",
        "app-connection.step2.title": "Activate App Connection",
        "app-connection.step2.desc": "Find the App Connection section on the institution settings page and click e-Eye ON button to activate the connection.",
        "app-connection.step3.title": "Check and Copy Institution Code",
        "app-connection.step3.desc": "Check and copy the unique institution code generated after activation. This code is used when members find the institution in the app.",
        "app-connection.step4.title": "Deliver Institution Code to Members",
        "app-connection.step4.desc": "Deliver the copied institution code to members via text or email or in person so they can enter it in the app.",
        "app-connection.step5.title": "Check Connection Status",
        "app-connection.step5.desc": "When members enter the institution code and connect in the app you can check the number of connected members and data in real-time on the DMS dashboard.",
        "app-connection.tip-title": "💡 CGM Connection Notes",
        "app-connection.tip-desc": "CGM device connection is set up by members directly in the app. Available device types and setup methods can be found in Settings > CGM Connection menu in the app.",
        "member-dashboard.title": "Member Dashboard",
        "member-dashboard.intro": "The member dashboard provides an overview of all members registered in the institution at a glance. Efficiently manage members through features like member list view and search and filtering.",
        "member-dashboard.guide-title": "Member Dashboard User Guide",
        "member-dashboard.step1.title": "View Member List",
        "member-dashboard.step1.desc": "Click Member Management from the left menu to display all registered members. Check basic information like name and registration date and last activity date.",
        "member-dashboard.step2.title": "Search and Filter Members",
        "member-dashboard.step2.desc": "Search members by name or email or phone number in the top search bar. Filter by status (active/inactive) or registration period etc.",
        "member-dashboard.step3.title": "Access Member Details",
        "member-dashboard.step3.desc": "Click on a member name to go to their detail page. Check basic info and diet records and nutrition analysis and consultation history etc.",
        "member-dashboard.step4.title": "Register New Member",
        "member-dashboard.step4.desc": "Click Add Member button to register a new member. Enter required information (name and contact) and an app login account will be automatically created.",
        "member-info.title": "Member Information Management",
        "member-info.intro": "View and edit individual member basic info and health info and goal settings etc. You can also check member electronic questionnaire responses and raw data.",
        "member-info.guide-title": "Member Information Management Guide",
        "member-info.step1.title": "Check Basic Information",
        "member-info.step1.desc": "Check member basic information including name and contact and email and birth date and gender. Click Edit button to update information.",
        "member-info.step2.title": "View Health Information",
        "member-info.step2.desc": "Check health-related information including height and weight and target weight and activity level and underlying conditions. Electronic questionnaire responses are automatically reflected.",
        "member-info.step3.title": "Check Raw Data",
        "member-info.step3.desc": "Check detailed data including member app usage logs and original diet record data. Use for data analysis.",
        "member-info.step4.title": "Set and Edit Goals",
        "member-info.step4.desc": "Set or edit member daily calorie goal (e.g. 2000kcal) and nutrient ratios and number of meals etc.",
        "member-info.step5.title": "Write Notes",
        "member-info.step5.desc": "Record notes about member special circumstances or consultation references. Other administrators can also view these notes.",
        "member-info.step6.title": "View 1:1 Chat History",
        "member-info.step6.desc": "View chat consultation history with member in chronological order. Reference previous consultations for continuous management.",
        "member-meal.title": "Meal Record Management",
        "member-meal.intro": "View and manage diet records that members logged in the SangsikPlus app. Check AI-analyzed nutrition information and edit if needed or provide feedback.",
        "member-meal.guide-title": "Meal Record Management Guide",
        "member-meal.step1.title": "View Diet Records",
        "member-meal.step1.desc": "View breakfast/lunch/dinner/snack records by member and date. Check in calendar view or list view.",
        "member-meal.step2.title": "Check Meal Photos",
        "member-meal.step2.desc": "Click on meal photos uploaded by members to view larger. Displayed along with the list of foods recognized by AI.",
        "member-meal.step3.title": "Check AI Nutrition Analysis Results",
        "member-meal.step3.desc": "Check calories and carbohydrates and protein and fat information automatically analyzed by AI. Detailed nutrition info per food item is also provided.",
        "member-meal.step4.title": "Edit Nutrition Information",
        "member-meal.step4.desc": "If AI analysis is inaccurate administrators can directly edit food type or amount to reflect accurate nutrition information.",
        "member-meal.step5.title": "Write and Send Feedback",
        "member-meal.step5.desc": "Write feedback on individual meals (positives and improvements and advice etc.). Written feedback is sent to member app with push notification.",
        "member-meal.step6.title": "Export Records",
        "member-meal.step6.desc": "Export diet records and nutrition analysis results for a specific period to Excel or PDF. Use as consultation materials.",
        "member-nutrition.title": "Nutrition Report",
        "member-nutrition.intro": "Generate and manage weekly/monthly reports analyzing member nutrition intake status. Visually check goal achievement rates and nutrient intake trends etc.",
        "member-nutrition.guide-title": "Nutrition Report Guide",
        "member-nutrition.step1.title": "Check Nutrition Intake Status",
        "member-nutrition.step1.desc": "Check member average calories and carbohydrates and protein and fat intake for the last 7 days. Goal achievement rate is displayed in graphs.",
        "member-nutrition.step2.title": "Check Blood Sugar Graph (CGM)",
        "member-nutrition.step2.desc": "For CGM-connected members check blood sugar change graphs before and after meals. Use to identify blood sugar spike periods.",
        "member-nutrition.step3.title": "Generate Weekly/Monthly Report",
        "member-nutrition.step3.desc": "Select a period and click Generate Report button to automatically create a comprehensive nutrition analysis report.",
        "member-nutrition.step4.title": "Download and Share Report",
        "member-nutrition.step4.desc": "Download the generated report as PDF or send it directly to members via email.",
        "member-nutrition.tip-title": "💡 Report Usage Tips",
        "member-nutrition.tip-desc": "Nutrition reports are effective when reviewed with members during regular consultations. Suggest diet improvement directions focusing on nutrients with low goal achievement rates.",
        "member-consult.title": "Online Consultation",
        "member-consult.intro": "Provides online consultation features including 1:1 chat consultation and electronic questionnaire response checking and consultation history management. Support personalized nutrition management with systematic consultation records.",
        "member-consult.guide-title": "Online Consultation Guide",
        "member-consult.step1.title": "1:1 Chat Consultation",
        "member-consult.step1.desc": "Check and respond to messages sent by members from the app. Communicate in real-time about meal photos and questions and health concerns etc.",
        "member-consult.step2.title": "Check Electronic Questionnaire Responses",
        "member-consult.step2.desc": "Check the electronic questionnaire content written by members. Includes information about health status and eating habits and allergies and medications etc.",
        "member-consult.step3.title": "View Consultation History",
        "member-consult.step3.desc": "View past consultation records with the member in chronological order. Provide consistent management by referencing previous consultation content.",
        "member-consult.step4.title": "Write Consultation Notes",
        "member-consult.step4.desc": "Record important content during consultation or matters to reference in future consultations as notes. Shared with other administrators.",
        "member-consult.step5.title": "Complete Consultation",
        "member-consult.step5.desc": "Click Complete button when consultation is finished. Consultation completion notification is sent to member and recorded in consultation history.",
        "member-consult.tip-title": "💡 Effective Consultation Tips",
        "member-consult.tip-desc": "Review member recent diet records and nutrition reports before consultation to provide more specific and personalized advice."
      }
    },
    "commonVisibility": {
      "login-admin.step1.visible": true,
      "login-admin.step1.image-visible": true,
      "login-admin.step2.visible": true,
      "login-admin.step2.image-visible": true,
      "login-admin.step3.visible": true,
      "login-admin.step3.image-visible": true,
      "login-admin.step4.visible": true,
      "login-admin.step4.image-visible": true,
      "login-admin.step5.visible": true,
      "login-admin.step5.image-visible": true,
      "login-admin.step6.visible": true,
      "login-admin.step6.image-visible": true,
      "login-member.step1.visible": true,
      "login-member.step1.image-visible": true,
      "login-member.step2.visible": true,
      "login-member.step2.image-visible": true,
      "login-member.step3.visible": true,
      "login-member.step3.image-visible": true,
      "login-member.step4.visible": true,
      "login-member.step4.image-visible": true,
      "login-member.step5.visible": true,
      "login-member.step5.image-visible": true,
      "login-member.step6.visible": true,
      "login-member.step6.image-visible": true,
      "app-intro.step1.visible": true,
      "app-intro.step1.image-visible": true,
      "app-intro.step2.visible": true,
      "app-intro.step2.image-visible": true,
      "app-intro.step3.visible": true,
      "app-intro.step3.image-visible": true,
      "app-intro.step4.visible": true,
      "app-intro.step4.image-visible": true,
      "app-intro.step5.visible": true,
      "app-intro.step5.image-visible": true,
      "app-intro.step6.visible": true,
      "app-intro.step6.image-visible": true,
      "app-connection.step1.visible": true,
      "app-connection.step1.image-visible": true,
      "app-connection.step2.visible": true,
      "app-connection.step2.image-visible": true,
      "app-connection.step3.visible": true,
      "app-connection.step3.image-visible": true,
      "app-connection.step4.visible": true,
      "app-connection.step4.image-visible": true,
      "app-connection.step5.visible": true,
      "app-connection.step5.image-visible": true,
      "app-connection.step6.visible": true,
      "app-connection.step6.image-visible": true,
      "member-dashboard.step1.visible": true,
      "member-dashboard.step1.image-visible": true,
      "member-dashboard.step2.visible": true,
      "member-dashboard.step2.image-visible": true,
      "member-dashboard.step3.visible": true,
      "member-dashboard.step3.image-visible": true,
      "member-dashboard.step4.visible": true,
      "member-dashboard.step4.image-visible": true,
      "member-dashboard.step5.visible": true,
      "member-dashboard.step5.image-visible": true,
      "member-dashboard.step6.visible": true,
      "member-dashboard.step6.image-visible": true,
      "member-info.step1.visible": true,
      "member-info.step1.image-visible": true,
      "member-info.step2.visible": true,
      "member-info.step2.image-visible": true,
      "member-info.step3.visible": true,
      "member-info.step3.image-visible": true,
      "member-info.step4.visible": true,
      "member-info.step4.image-visible": true,
      "member-info.step5.visible": true,
      "member-info.step5.image-visible": true,
      "member-info.step6.visible": true,
      "member-info.step6.image-visible": true,
      "member-meal.step1.visible": true,
      "member-meal.step1.image-visible": true,
      "member-meal.step2.visible": true,
      "member-meal.step2.image-visible": true,
      "member-meal.step3.visible": true,
      "member-meal.step3.image-visible": true,
      "member-meal.step4.visible": true,
      "member-meal.step4.image-visible": true,
      "member-meal.step5.visible": true,
      "member-meal.step5.image-visible": true,
      "member-meal.step6.visible": true,
      "member-meal.step6.image-visible": true,
      "member-nutrition.step1.visible": true,
      "member-nutrition.step1.image-visible": true,
      "member-nutrition.step2.visible": true,
      "member-nutrition.step2.image-visible": true,
      "member-nutrition.step3.visible": true,
      "member-nutrition.step3.image-visible": true,
      "member-nutrition.step4.visible": true,
      "member-nutrition.step4.image-visible": true,
      "member-nutrition.step5.visible": true,
      "member-nutrition.step5.image-visible": true,
      "member-nutrition.step6.visible": true,
      "member-nutrition.step6.image-visible": true,
      "member-consult.step1.visible": true,
      "member-consult.step1.image-visible": true,
      "member-consult.step2.visible": true,
      "member-consult.step2.image-visible": true,
      "member-consult.step3.visible": true,
      "member-consult.step3.image-visible": true,
      "member-consult.step4.visible": true,
      "member-consult.step4.image-visible": true,
      "member-consult.step5.visible": true,
      "member-consult.step5.image-visible": true,
      "member-consult.step6.visible": true,
      "member-consult.step6.image-visible": true
    },
    "pageMetadata": {
      "start-features": {
        "layout": "features"
      },
      "login-admin": {
        "layout": "default"
      },
      "login-member": {
        "layout": "default"
      },
      "app-intro": {
        "layout": "default"
      },
      "app-connection": {
        "layout": "default"
      },
      "member-dashboard": {
        "layout": "default"
      },
      "member-info": {
        "layout": "default"
      },
      "member-meal": {
        "layout": "default"
      },
      "member-nutrition": {
        "layout": "default"
      },
      "member-consult": {
        "layout": "default"
      },
      "recipe-create": {
        "layout": "default"
      },
      "recipe-manage": {
        "layout": "default"
      },
      "settings-institution": {
        "layout": "default"
      },
      "settings-members": {
        "layout": "default"
      },
      "settings-etc": {
        "layout": "default"
      },
      "notice-list": {
        "layout": "accordion",
        "translationKey": "notice-list"
      }
    },
    "menuStructure": [
      {
        "id": "start",
        "pages": [
          "start-features"
        ]
      },
      {
        "id": "login",
        "pages": [
          "login-admin",
          "login-member"
        ]
      },
      {
        "id": "app",
        "pages": [
          "app-intro",
          "app-connection"
        ]
      },
      {
        "id": "member",
        "pages": [
          "member-dashboard",
          "member-info",
          "member-meal",
          "member-nutrition",
          "member-consult"
        ]
      },
      {
        "id": "recipe",
        "pages": [
          "recipe-create",
          "recipe-manage"
        ]
      },
      {
        "id": "settings",
        "pages": [
          "settings-institution",
          "settings-members",
          "settings-etc"
        ]
      },
      {
        "id": "notice",
        "pages": [
          "notice-list"
        ]
      }
    ],
    "updatedAt": "2024-12-01T00:00:00.000Z"
  }'::jsonb
)
ON CONFLICT (key) 
DO UPDATE SET value = EXCLUDED.value;

-- ============================================
-- 실행 완료 확인 쿼리
-- ============================================
-- 저장된 데이터 확인:
-- SELECT key, jsonb_pretty(value) FROM kv_store_8aea8ee5 WHERE key = 'dms_manual_data_v1';
